server:
  # 端口
  port: 83

spring:
  motan:
    # 扫描Motan注解包
    annotation:
      package: github.com.passerr.motan.api.impl
      # 多包扫描
      # pakcages:
      # - package1
      # - package2
    # 注册中心配置
    registry:
      name: motan-server-registry
      regProtocol: zookeeper
      address: 127.0.0.1:2181
    # 服务端共同配置
    basic-service:
        application: motan-server-demo
        check: true
        accessLog: false
        requestTimeout: 10000